// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQExpmZLNgZxPnad9cbNhstWnCWwzBSc',
    appId: '1:605143010599:web:2dfe48ab84e43e91c1ad02',
    messagingSenderId: '605143010599',
    projectId: 'quiz-e9c65',
    authDomain: 'quiz-e9c65.firebaseapp.com',
    storageBucket: 'quiz-e9c65.firebasestorage.app',
    measurementId: 'G-CM2Z6KDW8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALkwFhhcYgqogVZpU9Xd_WwibiLdSCJaI',
    appId: '1:605143010599:android:b47fd502a9e4b229c1ad02',
    messagingSenderId: '605143010599',
    projectId: 'quiz-e9c65',
    storageBucket: 'quiz-e9c65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5yDEK4NT5RjbpDsIu06oky8u_rGFoBzA',
    appId: '1:605143010599:ios:2344d5e2863be6e2c1ad02',
    messagingSenderId: '605143010599',
    projectId: 'quiz-e9c65',
    storageBucket: 'quiz-e9c65.firebasestorage.app',
    iosClientId: '605143010599-0p16lpj0kqg41nb23nnlrglr5lgc6kt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5yDEK4NT5RjbpDsIu06oky8u_rGFoBzA',
    appId: '1:605143010599:ios:2344d5e2863be6e2c1ad02',
    messagingSenderId: '605143010599',
    projectId: 'quiz-e9c65',
    storageBucket: 'quiz-e9c65.firebasestorage.app',
    iosClientId: '605143010599-0p16lpj0kqg41nb23nnlrglr5lgc6kt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNQExpmZLNgZxPnad9cbNhstWnCWwzBSc',
    appId: '1:605143010599:web:db3886ba665cd6d7c1ad02',
    messagingSenderId: '605143010599',
    projectId: 'quiz-e9c65',
    authDomain: 'quiz-e9c65.firebaseapp.com',
    storageBucket: 'quiz-e9c65.firebasestorage.app',
    measurementId: 'G-GE09LB640Z',
  );

}